# use java support
language: java

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      if: branch = master OR tag =~ ^8\.[0-9]+\.[0-9]+ # match 8.x.x
    - jdk: openjdk11
      if: branch = 9.0.0 OR tag =~ ^[0-9]+[0-9]+\.[0-9]+\.[0-9]+ # match xx.x.x

# run in container
sudo: false

# use linux as operating system
os: linux
dist: trusty

# Do not run travis install step `./gradlew assemble`
install: true

# Assemble jars
script: ./gradlew clean assemble -Ptransifex.api=$TRANSIFEX_API

cache:
  directories:
    - $HOME/.gradle/caches/

deploy:
  # Deploy snapshots on every commit made to master and 9.0.0 branch
  - provider: script
    script: bash .ci/deploy-snapshot.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ master|9.0.0

  # Deploy releases on every tag push
  - provider: script
    script: bash .ci/deploy.sh
    skip_cleanup: true
    on:
      tags: true