# This is a sample build configuration for Gradle.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: openjdk:8

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - chmod +x gradlew
          - ./gradlew build