pipelines:
  branches:
    default:
      - step:
          name: Build and assemble default branch
          image: cogniteev/oracle-java:java8
          caches:
            - gradle
          script:
            - chmod +x gradlew
            - ./gradlew clean assemble uploadPublished -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD -Ptransifex.api=$TRANSIFEX_API
    9.0.0:
      - step:
          name: Build and assemble 9.0.0 branch
          image: abhinay/oracle-java:java10
          caches:
            - gradle
          script:
            - chmod +x gradlew
            - ./gradlew clean assemble uploadPublished -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD -Ptransifex.api=$TRANSIFEX_API

  bookmarks:
    'release/8*':
      - step:
          name: Build and release
          image: cogniteev/oracle-java:java8
          caches:
            - gradle
          script:
          - chmod +x gradlew .ci/update.sh .ci/commit.sh
          - ./.ci/update.sh
          - ./gradlew clean assemble uploadPublished -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD -Ptransifex.api=$TRANSIFEX_API
          - ./.ci/commit.sh
    'release/9*':
      - step:
          name: Build and release
          image: abhinay/oracle-java:java10
          caches:
            - gradle
          script:
          - chmod +x gradlew .ci/update.sh .ci/commit.sh
          - ./.ci/update.sh
          - ./gradlew clean assemble uploadPublished -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD -Ptransifex.api=$TRANSIFEX_API
          - ./.ci/commit.sh